/*
 * Candy Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

type Order struct {
	Money int32 `json:"money"`
	CandyType string `json:"candyType"`
	CandyCount int32 `json:"candyCount"`
}
